//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipPurSEditionBuilder.Language {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalMessageStrings_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalMessageStrings_ru_RU() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipPurSEditionBuilder.Language.GlobalMessageStrings_ru_RU", typeof(GlobalMessageStrings_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступна новая версия программы.
        /// </summary>
        internal static string AccessNew {
            get {
                return ResourceManager.GetString("AccessNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте хотя бы один кошелёк в базу данных.
        /// </summary>
        internal static string BasePurse {
            get {
                return ResourceManager.GetString("BasePurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bitcoin адресс скопирован..
        /// </summary>
        internal static string BitCopy {
            get {
                return ResourceManager.GetString("BitCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Билд создан успешно!.
        /// </summary>
        internal static string BuildCreated {
            get {
                return ResourceManager.GetString("BuildCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущая версия ПО:.
        /// </summary>
        internal static string CurrentVer {
            get {
                return ResourceManager.GetString("CurrentVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные добавлены!.
        /// </summary>
        internal static string DataAdd {
            get {
                return ResourceManager.GetString("DataAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные загружены!.
        /// </summary>
        internal static string DataLoader {
            get {
                return ResourceManager.GetString("DataLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные сохранены!.
        /// </summary>
        internal static string DataSave {
            get {
                return ResourceManager.GetString("DataSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия .dll не совпадает!.
        /// </summary>
        internal static string DLLNotCorrect {
            get {
                return ResourceManager.GetString("DLLNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните поля.
        /// </summary>
        internal static string EmptySave {
            get {
                return ResourceManager.GetString("EmptySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при копирование..
        /// </summary>
        internal static string ErrorBitCopy {
            get {
                return ResourceManager.GetString("ErrorBitCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при создание билда!.
        /// </summary>
        internal static string ErrorBuild {
            get {
                return ResourceManager.GetString("ErrorBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет подключения к серверу.
        /// </summary>
        internal static string ErrorConnect {
            get {
                return ResourceManager.GetString("ErrorConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка проверки лицензии.
        /// </summary>
        internal static string ErrorLicense {
            get {
                return ResourceManager.GetString("ErrorLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки данных.
        /// </summary>
        internal static string ErrorLoader {
            get {
                return ResourceManager.GetString("ErrorLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сохранения данных.
        /// </summary>
        internal static string ErrorSave {
            get {
                return ResourceManager.GetString("ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите расширение.
        /// </summary>
        internal static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все поля отчищены..
        /// </summary>
        internal static string FieldsClean {
            get {
                return ResourceManager.GetString("FieldsClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не обнаружен!.
        /// </summary>
        internal static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните все поля!.
        /// </summary>
        internal static string FillFields {
            get {
                return ResourceManager.GetString("FillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас последняя версия билдера.
        /// </summary>
        internal static string FinalVersionMessage {
            get {
                return ResourceManager.GetString("FinalVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на app.Manifest не обнаружен!.
        /// </summary>
        internal static string FindManifest {
            get {
                return ResourceManager.GetString("FindManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите иконку для билд файла.
        /// </summary>
        internal static string IconChoice {
            get {
                return ResourceManager.GetString("IconChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш ключ доступа:.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус лицензии:  Активировано.
        /// </summary>
        internal static string LicenseActivate {
            get {
                return ResourceManager.GetString("LicenseActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус лицензии:  Не активировано.
        /// </summary>
        internal static string LicenseNoActivate {
            get {
                return ResourceManager.GetString("LicenseNoActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Папка Mod или файл *CLI.exe не найдены!.
        /// </summary>
        internal static string ModCLI {
            get {
                return ResourceManager.GetString("ModCLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mono.Cecil.dll не найден!.
        /// </summary>
        internal static string MonoFind {
            get {
                return ResourceManager.GetString("MonoFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая версия ПО:.
        /// </summary>
        internal static string NewVer {
            get {
                return ResourceManager.GetString("NewVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иконка не выбрана!.
        /// </summary>
        internal static string NoIconChoice {
            get {
                return ResourceManager.GetString("NoIconChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Билд обфусцирован!.
        /// </summary>
        internal static string Obfuscated {
            get {
                return ResourceManager.GetString("Obfuscated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начинается перезапуск билдера.
        /// </summary>
        internal static string RestartBuild {
            get {
                return ResourceManager.GetString("RestartBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер иконки:.
        /// </summary>
        internal static string SizeIcon {
            get {
                return ResourceManager.GetString("SizeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновления загружены!.
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя:.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия:.
        /// </summary>
        internal static string VerSoftware {
            get {
                return ResourceManager.GetString("VerSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро Пожаловать.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
